const BANKNOTE_SRC='./banknotes-source.jpg?v=2';
const canvas=document.getElementById('gl'),status=document.getElementById('status'),gl=canvas.getContext('webgl',{antialias:true,alpha:true,powerPreference:'high-performance'});if(!gl){status.textContent='WebGL לא זמין';throw new Error('no webgl')}
function shader(type,src){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}function program(v,f){let p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,v));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p}
const VS='precision highp float;attribute vec3 aPos;attribute vec2 aUV;attribute vec3 aNormal;uniform mat4 uMVP;uniform mat4 uModel;varying vec2 vUV;varying vec3 vN;void main(){vUV=aUV;vN=normalize(mat3(uModel)*aNormal);gl_Position=uMVP*vec4(aPos,1.0);}';
const FS='precision highp float;varying vec2 vUV;varying vec3 vN;uniform sampler2D uTex;uniform vec3 uTint;uniform float uUseTex;void main(){float topFace=step(.72,abs(vN.y));float stripes=.92+.08*sin(vUV.y*210.0);vec3 paper=vec3(.88,.83,.74)*stripes;vec3 texc=texture2D(uTex,vUV).rgb;vec3 base=mix(paper,texc,uUseTex*topFace);float key=.62+.38*max(dot(normalize(vN),normalize(vec3(.32,.82,.48))),0.0);float rim=.12*pow(1.0-max(abs(vN.z),0.0),2.0);gl_FragColor=vec4(base*uTint*(key+rim),1.0);}';
const BFS='precision highp float;varying vec2 vUV;varying vec3 vN;uniform sampler2D uFront;uniform sampler2D uBack;void main(){vec4 c=gl_FrontFacing?texture2D(uFront,vUV):texture2D(uBack,vec2(1.0-vUV.x,vUV.y));float l=.72+.28*max(dot(normalize(vN),normalize(vec3(.25,.8,.5))),0.0);gl_FragColor=vec4(c.rgb*l,c.a);}';
const P=program(VS,FS),BP=program(VS,BFS);function loc(p){return{pos:gl.getAttribLocation(p,'aPos'),uv:gl.getAttribLocation(p,'aUV'),n:gl.getAttribLocation(p,'aNormal'),mvp:gl.getUniformLocation(p,'uMVP'),model:gl.getUniformLocation(p,'uModel'),tex:gl.getUniformLocation(p,'uTex'),tint:gl.getUniformLocation(p,'uTint'),use:gl.getUniformLocation(p,'uUseTex'),front:gl.getUniformLocation(p,'uFront'),back:gl.getUniformLocation(p,'uBack')}}const L=loc(P),BL=loc(BP);
function texFromCanvas(cv){let t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,cv);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return t}
function loadCrops(url){return new Promise((resolve,reject)=>{let im=new Image();im.onload=()=>{const R={f200:[.02546,.33333,.47383,.10091],b200:[.50495,.33333,.46393,.10091],f100:[.05233,.43945,.44554,.09896],b100:[.50778,.43945,.45969,.09961]};function one(r){let cv=document.createElement('canvas');cv.width=1000;cv.height=470;let x=cv.getContext('2d');x.drawImage(im,r[0]*im.width,r[1]*im.height,r[2]*im.width,r[3]*im.height,0,0,cv.width,cv.height);return texFromCanvas(cv)}resolve([one(R.f100),one(R.b100),one(R.f200),one(R.b200)])};im.onerror=reject;im.src=url})}
function mesh(pos,uv,nor,idx,dyn=false){let m={count:idx.length,pos:new Float32Array(pos)};for(const [key,arr] of [['pb',m.pos],['ub',new Float32Array(uv)],['nb',new Float32Array(nor)]]){m[key]=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,m[key]);gl.bufferData(gl.ARRAY_BUFFER,arr,key==='pb'&&dyn?gl.DYNAMIC_DRAW:gl.STATIC_DRAW)}m.ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,m.ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(idx),gl.STATIC_DRAW);return m}
function bind(m,l){for(const [b,a,size] of [[m.pb,l.pos,3],[m.ub,l.uv,2],[m.nb,l.n,3]]){gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,size,gl.FLOAT,false,0,0)}gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,m.ib)}
function cube(){let p=[],u=[],n=[],idx=[],faces=[[[0,0,1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]],[[0,0,-1],[1,-1,-1],[-1,-1,-1],[-1,1,-1],[1,1,-1]],[[0,1,0],[-1,1,1],[1,1,1],[1,1,-1],[-1,1,-1]],[[0,-1,0],[-1,-1,-1],[1,-1,-1],[1,-1,1],[-1,-1,1]],[[1,0,0],[1,-1,1],[1,-1,-1],[1,1,-1],[1,1,1]],[[-1,0,0],[-1,-1,-1],[-1,-1,1],[-1,1,1],[-1,1,-1]]];faces.forEach((f,fi)=>{let b=p.length/3;for(let j=1;j<5;j++){p.push(...f[j]);n.push(...f[0]);let q=[[0,0],[1,0],[1,1],[0,1]][j-1];u.push(...q)}idx.push(b,b+1,b+2,b,b+2,b+3)});return mesh(p,u,n,idx)}
function plane(nx=14,ny=5){let p=[],u=[],n=[],idx=[];for(let y=0;y<=ny;y++)for(let x=0;x<=nx;x++){let a=x/nx,b=y/ny;p.push((a-.5)*2,(b-.5),0);u.push(a,b);n.push(0,0,1)}for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){let a=y*(nx+1)+x,b=a+1,c=a+nx+1,d=c+1;idx.push(a,b,d,a,d,c)}return mesh(p,u,n,idx,true)}
function cyl(seg=20){let p=[],u=[],n=[],idx=[];for(let y=0;y<=1;y++){for(let i=0;i<=seg;i++){let a=i/seg*Math.PI*2,x=Math.cos(a),z=Math.sin(a);p.push(x,y*2-1,z);u.push(i/seg,y);n.push(x,0,z)}}for(let i=0;i<seg;i++){let a=i,b=i+1,c=a+seg+1,d=c+1;idx.push(a,b,d,a,d,c)}let top=p.length/3;p.push(0,1,0);u.push(.5,.5);n.push(0,1,0);let bot=p.length/3;p.push(0,-1,0);u.push(.5,.5);n.push(0,-1,0);for(let i=0;i<seg;i++){let a=i,b=i+1,ta=seg+1+i,tb=ta+1;idx.push(top,ta,tb);idx.push(bot,b,a)}return mesh(p,u,n,idx)}
const C=cube(),Q=plane(),CY=cyl();
function I(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}function M(a,b){let o=new Array(16).fill(0);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o}function T(x,y,z){let m=I();m[12]=x;m[13]=y;m[14]=z;return m}function S(x,y,z){let m=I();m[0]=x;m[5]=y;m[10]=z;return m}function RX(a){let c=Math.cos(a),s=Math.sin(a),m=I();m[5]=c;m[6]=s;m[9]=-s;m[10]=c;return m}function RY(a){let c=Math.cos(a),s=Math.sin(a),m=I();m[0]=c;m[2]=-s;m[8]=s;m[10]=c;return m}function RZ(a){let c=Math.cos(a),s=Math.sin(a),m=I();m[0]=c;m[1]=s;m[4]=-s;m[5]=c;return m}function Pers(f,a,n,z){let q=1/Math.tan(f/2),nf=1/(n-z);return[q/a,0,0,0,0,q,0,0,0,0,(z+n)*nf,-1,0,0,2*z*n*nf,0]}function Look(ex,ey,ez,cx,cy,cz){let zx=ex-cx,zy=ey-cy,zz=ez-cz,l=Math.hypot(zx,zy,zz);zx/=l;zy/=l;zz/=l;let xx=-zz,xz=zx;l=Math.hypot(xx,xz);xx/=l;xz/=l;let yx=-xz*zy,yy=xz*zx-xx*zz,yz=xx*zy;return[xx,yx,zx,0,0,yy,zy,0,xz,yz,zz,0,-(xx*ex+xz*ez),-(yx*ex+yy*ey+yz*ez),-(zx*ex+zy*ey+zz*ez),1]}function rnd(n){let x=Math.sin(n*91.733)*43758.5453;return x-Math.floor(x)}
let VP;
function drawBox(model,tex,tint,useTex){gl.useProgram(P);bind(C,L);gl.uniformMatrix4fv(L.model,false,new Float32Array(model));gl.uniformMatrix4fv(L.mvp,false,new Float32Array(M(VP,model)));gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tex);gl.uniform1i(L.tex,0);gl.uniform3fv(L.tint,new Float32Array(tint));gl.uniform1f(L.use,useTex);gl.drawElements(gl.TRIANGLES,C.count,gl.UNSIGNED_SHORT,0)}
function drawBill(model,front,back){gl.useProgram(BP);bind(Q,BL);gl.uniformMatrix4fv(BL.model,false,new Float32Array(model));gl.uniformMatrix4fv(BL.mvp,false,new Float32Array(M(VP,model)));gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,front);gl.uniform1i(BL.front,0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,back);gl.uniform1i(BL.back,1);gl.disable(gl.CULL_FACE);gl.drawElements(gl.TRIANGLES,Q.count,gl.UNSIGNED_SHORT,0);gl.enable(gl.CULL_FACE)}
loadCrops(BANKNOTE_SRC).then(([a,b,c,d])=>{
  let bundles=[],coins=[],k=0;
  let layers=[[44,4.25,.44,.90],[36,3.65,.72,.86],[29,3.08,1.00,.82],[23,2.58,1.28,.78],[18,2.10,1.56,.73],[14,1.67,1.84,.68],[10,1.24,2.12,.63],[7,.88,2.39,.58],[4,.48,2.66,.52]];
  for(let li=0;li<layers.length;li++){let[n,r,y,s0]=layers[li];for(let j=0;j<n;j++,k++){let ang=rnd(k+2)*Math.PI*2,rr=r*Math.sqrt(rnd(k+5))*(.72+.28*rnd(k+8));bundles.push({x:Math.cos(ang)*rr+(rnd(k+11)-.5)*.22,y:y+(rnd(k+14)-.5)*.18,z:Math.sin(ang)*rr+(rnd(k+17)-.5)*.22,ry:rnd(k+20)*Math.PI*2,rz:(rnd(k+23)-.5)*.18,s:s0*(.91+.18*rnd(k+26)),tex:k%3===0?a:c})}}
  for(let i=0;i<52;i++){let ang=rnd(i+500)*Math.PI*2,rr=.8+rnd(i+510)*4.0;coins.push({x:Math.cos(ang)*rr,y:.12+rnd(i+520)*.75,z:Math.sin(ang)*rr,rx:Math.PI/2+(rnd(i+530)-.5)*.5,ry:rnd(i+540)*Math.PI,rz:(rnd(i+550)-.5)*.6,s:.10+rnd(i+560)*.09})}
  let flyers=[];for(let i=0;i<14;i++)flyers.push({ph:rnd(i+300)*Math.PI*2,sp:.15+rnd(i+310)*.11,r:4.9+rnd(i+320)*1.5,h:2.6+rnd(i+330)*3.0,tilt:(rnd(i+340)-.5)*.65,sc:.50+rnd(i+350)*.28,fr:i%3===0?a:c,ba:i%3===0?b:d});
  let yaw=-.18,ty=-.18,drag=false,sx=0;
  canvas.addEventListener('pointerdown',e=>{drag=true;sx=e.clientX;canvas.setPointerCapture(e.pointerId)});
  canvas.addEventListener('pointermove',e=>{if(!drag)return;ty+=(e.clientX-sx)*.005;sx=e.clientX});
  canvas.addEventListener('pointerup',()=>drag=false);
  let start=performance.now();
  function frame(now){
    let w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio,2),t=(now-start)/1000;
    if(canvas.width!==Math.floor(w*dpr)||canvas.height!==Math.floor(h*dpr)){canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);gl.viewport(0,0,canvas.width,canvas.height)}
    gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);
    yaw+=(ty-yaw)*.08;VP=M(Pers(.64,w/h,.1,100),Look(0,6.4,h>w?18.7:15.8,0,1.55,0));let root=RY(yaw);
    for(let i=0;i<16;i++){let ang=i/16*Math.PI*2;drawBox(M(root,M(T(Math.cos(ang)*3.4,-.12,Math.sin(ang)*3.4),M(RY(-ang),S(1.60,.075,1.15)))),a,[.16,.12,.10],0)}
    for(const x of bundles)drawBox(M(root,M(T(x.x,x.y,x.z),M(RY(x.ry),M(RZ(x.rz),S(1.50*x.s,.10*x.s,.70*x.s))))),x.tex,[1,1,1],1);
    for(const c0 of coins){let CM=M(root,M(T(c0.x,c0.y,c0.z),M(RX(c0.rx),M(RY(c0.ry),M(RZ(c0.rz),S(c0.s,.035,c0.s))))));gl.useProgram(P);bind(CY,L);gl.uniformMatrix4fv(L.model,false,new Float32Array(CM));gl.uniformMatrix4fv(L.mvp,false,new Float32Array(M(VP,CM)));gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,a);gl.uniform1i(L.tex,0);gl.uniform3fv(L.tint,new Float32Array([.84,.60,.18]));gl.uniform1f(L.use,0);gl.drawElements(gl.TRIANGLES,CY.count,gl.UNSIGNED_SHORT,0)}
    for(const f of flyers){let arr=Q.pos.slice();for(let vi=0;vi<arr.length/3;vi++){let q=vi*3,bx=arr[q],by=arr[q+1];arr[q+2]=Math.sin(bx*3.7+t*3.0+f.ph)*.10+Math.sin(by*6+t*2.2+f.ph)*.035}gl.bindBuffer(gl.ARRAY_BUFFER,Q.pb);gl.bufferSubData(gl.ARRAY_BUFFER,0,arr);let ang=f.ph+t*f.sp,model=M(T(Math.cos(ang)*f.r,f.h+Math.sin(t*.9+f.ph)*.42,Math.sin(ang)*f.r),M(RY(ang+Math.PI/2),M(RX(Math.sin(t*.7+f.ph)*.2),M(RZ(Math.sin(t*1.2+f.ph)*.27+f.tilt),S(1.28*f.sc,.76*f.sc,1)))));drawBill(model,f.fr,f.ba)}
    status.textContent='3D פעיל • '+bundles.length+' חבילות • '+coins.length+' מטבעות • '+flyers.length+' שטרות חיים';
    requestAnimationFrame(frame)
  }
  requestAnimationFrame(frame)
}).catch(e=>{status.textContent='שגיאה: '+e.message;console.error(e)});